### ISSUE TITLE
Elliptic Curve not generating

### ISSUE THREAD

**Issue by ndonohoe-bjss** [mitreid-connect/mkjwk.org#1]
On https://mkjwk.org/ using Elliptic Curve no keys are generated, all three boxes just show `Loading...` indefinitely

**Comment by danielwegener** [comment]
Request URL: `https://mkjwk.org/jwk/ec?crv=P-256&use=sig&alg=ES256&kid=kid`

Response body: `{"timestamp":1490279665766,"status":500,"error":"Internal Server Error","exception":"java.lang.IllegalArgumentException","message":"The JWK must not be null"}`

**Comment by jricher** [comment]
I think the server was upgraded and the version of Java needs to have its non-US provider turned back on. Thanks for the reminder.
