### ISSUE TITLE
Alg field for encryption keys doesn't appear to give correct options

### ISSUE THREAD

**Issue by chadlwilson** [mitreid-connect/mkjwk.org#18]
Firstly, great little tool here! Thanks!

One observation I have is that if you choose to generate an encryption-usage key, the `alg` choices and generated key appears to be incorrect, and populates with JW**S** algs (`RS256`, `ES256` etc)

While alg is optional in general, for encryption keys, believe these should be `RSA-OAEP-256`, `ECDH-ES`, `ECDS-ES+A256KW` etc per https://tools.ietf.org/html/rfc7518#section-4.1

**Comment by jricher** [comment]
Good observation, right now the tool doesn't take into account the "use" field when making values available for the other fields, and the `alg` field pulls from a list of JWS values. we can look at adding that, or a pull request would be appreciated if you can!

**Comment by jricher** [comment]
I put in a fix for this and it's been pushed to the website. If there are any issues like missing or miscategorized algorithms, just file another issue or PR. Thanks!

**Comment by chadlwilson** [comment]
Wow, thanks! Hadn't got around to looking at it yet 👍
