### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by spallem1** [mitreid-connect/mkjwk.org#23]
Hello, I like this tool and was planning to use it for internal use. I do not see a license file for this package. I'm assuming it is Apache 2.0 but want to check. It would be nice if the license file is in the package.

**Comment by jricher** [comment]
Are you looking to include the website itself or the key generator? The underlying library and CLI wrapper are licensed under the Apache license. https://github.com/mitreid-connect/json-web-key-generator

The website doesn't have a license applied but we didn't expect anyone would want to incorporate it. I would be fine with putting it under Apache if that's your intent (and we should probably put one up anyway).

**Comment by jricher** [comment]
added
