### ISSUE TITLE
Adding support for defining bytesize of keys

### ISSUE THREAD

**Issue by Magnusri** [mitreid-connect/mkjwk.org#4]
Hello!

Would you consider adding an option to specify the bytesize of the generated x, y and d keys?
I can't find any generator able to do this.. I need the x, y and d at exactly 32 or 48 bytes.. Any idea as of how to accomplish this?

I know it is a bit wierd place to be posting a question, but thanks for any help!

Thank you
Magnus

**Comment by jricher** [comment]
This would need to be fixed in the underlying library, json-web-key-generator. There the keys are generated using a keyspec, which I don't think allows that level of flexiblity in java. If you can put a pull request on that project to allow that then the functionality could be exposed here.
